# https://taskfile.dev

version: "3"

vars:
  PACKAGES:
    [
      ansi,
      cellbuf,
      colors,
      conpty,
      editor,
      errors,
      examples,
      exp/golden,
      exp/higherorder,
      exp/maps,
      exp/open,
      exp/ordered,
      exp/slice,
      exp/strings,
      exp/teatest,
      exp/teatest/v2,
      input,
      json,
      sshkey,
      term,
      termios,
      vt,
      wcwidth,
      windows,
      xpty,
    ]

tasks:
  fmt:
    desc: 为所有包运行 gofumpt 格式化
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && gofmt -s -w .

  modernize:
    desc: 为所有包运行 modernize 现代化
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && modernize -fix ./...

  lint:
    desc: 为所有包运行基础代码检查
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && golangci-lint run

  test:
    desc: 为所有包运行测试
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && go test ./... {{.CLI_ARGS}}

  tidy:
    desc: 为所有包运行 `go mod tidy` 清理依赖
    cmds:
      - for: { var: PACKAGES }
        cmd: cd {{.ITEM}} && go mod tidy
