#!/usr/bin/env bash

# shellcheck disable=SC2016
find . -type f -name go.mod | sort | while read -r mod; do
  dir="$(dirname "$mod")"
  name="$(basename "$dir")"
  # 当模块以语义化版本风格嵌套时，获取父目录
  if [[ "$name" =~ ^v[0-9]+.*$ ]]; then
    ver="$(basename "$dir")"
    dir="$(dirname "$dir")"
    name="$(basename "$dir")-$ver"
  fi

  sum="$dir/go.sum"
  echo "# 由 scripts/builds 自动生成。请勿编辑。
name: $name

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - $(dirname "$mod" | cut -f2- -d/)/**
      - .github/workflows/${name}.yml

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: \${{ matrix.os }}
    defaults:
      run:
        working-directory: $(dirname "$mod")
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: actions/setup-go@v6
        with:
          go-version-file: $mod
          cache: true
          cache-dependency-path: $sum
      - run: go build -v ./...
      - run: |
          go test -race -covermode=atomic -coverprofile='coverage.txt' ./...
      - uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          token: \${{ secrets.CODECOV_TOKEN }}

  dependabot:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: \${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "\${{ secrets.GITHUB_TOKEN }}"
      - run: |
          gh pr review --approve "\$PR_URL"
          gh pr merge --squash --auto "\$PR_URL"
        env:
          PR_URL: \${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: \${{secrets.GITHUB_TOKEN}}

  lint:
    uses: purpose168/meta-cn/.github/workflows/lint.yml@main
    with:
      directory: $(dirname "$mod" | cut -f2- -d/)

" >"./.github/workflows/${name}.yml"
done
