#!/usr/bin/env bash

echo '# 由 scripts/dependabot 自动生成。请勿编辑。

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"' >./.github/dependabot.yml

find . -type f -name go.mod | cut -f2- -d'/' | sort | while read -r mod; do
  echo '
  - package-ecosystem: "gomod"
    directory: "/'"$(dirname "$mod")"'"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"' >>./.github/dependabot.yml
done
